services:
  app:
    image: sportapi-app
    build: .

  caddy:
    image: sportapi-caddy
    build: server/services/caddy
    depends_on:
      - app
    ports:
      - 4000:443
      - 4000:443/udp
    volumes:
      - caddy_data:/data
      - $PWD/server/services/caddy/Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
